'use client';

import { useEffect, useState } from 'react';
import { Navbar } from '@/components/Navbar';
import { EmptyState } from '@/components/EmptyState';
import { ErrorState } from '@/components/ErrorState';
import { LoadingState } from '@/components/LoadingState';
import { api, Notification } from '@/services/api';

export default function NotificationsPage() { const [items, setItems] = useState<Notification[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const load = () => api.getNotifications().then(result => setItems(result.data)).catch((requestError: any) => setError(requestError.message || 'Unable to load notifications.')).finally(() => setLoading(false)); useEffect(() => { load(); }, []); const markAll = async () => { await api.markAllNotificationsRead(); setItems(current => current.map(item => ({ ...item, isRead: true }))); }; return <div className="min-h-screen bg-slate-950 text-slate-100"><Navbar /><main className="max-w-3xl mx-auto px-4 py-8 space-y-6"><div className="flex items-end justify-between"><div><h1 className="text-3xl font-extrabold text-white">Notifications</h1><p className="text-sm text-slate-400 mt-2">Updates about claims, matches, and handovers.</p></div><button onClick={markAll} className="text-xs font-semibold text-blue-400 hover:text-blue-300">Mark all read</button></div>{loading ? <LoadingState message="Loading notifications..." /> : error ? <ErrorState message={error} onRetry={load} /> : items.length === 0 ? <EmptyState title="No notifications" description="Important workflow updates will appear here." /> : <div className="space-y-2">{items.map(item => <button key={item.id} onClick={async () => { if (!item.isRead) { await api.markNotificationRead(item.id); setItems(current => current.map(candidate => candidate.id === item.id ? { ...candidate, isRead: true } : candidate)); } }} className={`w-full rounded-xl border p-4 text-left ${item.isRead ? 'border-slate-800 bg-slate-900' : 'border-blue-500/30 bg-blue-500/10'}`}><div className="flex justify-between gap-4"><p className="font-semibold text-white">{item.title}</p><span className="text-[11px] text-slate-500">{new Date(item.createdAt).toLocaleString()}</span></div><p className="text-sm text-slate-300 mt-2">{item.message}</p></button>)}</div>}</main></div>; }